version: '3.1'

services:
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080